#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DictUyCn")]
public partial class dcDictDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertTCnUy(TCnUy instance);
  partial void UpdateTCnUy(TCnUy instance);
  partial void DeleteTCnUy(TCnUy instance);
  partial void InsertTUyCn(TUyCn instance);
  partial void UpdateTUyCn(TUyCn instance);
  partial void DeleteTUyCn(TUyCn instance);
  #endregion
	
	public dcDictDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DictUyCnConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public dcDictDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dcDictDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dcDictDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dcDictDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<TCnUy> TCnUys
	{
		get
		{
			return this.GetTable<TCnUy>();
		}
	}
	
	public System.Data.Linq.Table<TUyCn> TUyCns
	{
		get
		{
			return this.GetTable<TUyCn>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TCnUy")]
public partial class TCnUy : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _WordCn;
	
	private string _WordPinyin;
	
	private string _WordUy;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnWordCnChanging(string value);
    partial void OnWordCnChanged();
    partial void OnWordPinyinChanging(string value);
    partial void OnWordPinyinChanged();
    partial void OnWordUyChanging(string value);
    partial void OnWordUyChanged();
    #endregion
	
	public TCnUy()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordCn", DbType="NChar(255)")]
	public string WordCn
	{
		get
		{
			return this._WordCn;
		}
		set
		{
			if ((this._WordCn != value))
			{
				this.OnWordCnChanging(value);
				this.SendPropertyChanging();
				this._WordCn = value;
				this.SendPropertyChanged("WordCn");
				this.OnWordCnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordPinyin", DbType="NChar(255)")]
	public string WordPinyin
	{
		get
		{
			return this._WordPinyin;
		}
		set
		{
			if ((this._WordPinyin != value))
			{
				this.OnWordPinyinChanging(value);
				this.SendPropertyChanging();
				this._WordPinyin = value;
				this.SendPropertyChanged("WordPinyin");
				this.OnWordPinyinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordUy", DbType="NChar(255)")]
	public string WordUy
	{
		get
		{
			return this._WordUy;
		}
		set
		{
			if ((this._WordUy != value))
			{
				this.OnWordUyChanging(value);
				this.SendPropertyChanging();
				this._WordUy = value;
				this.SendPropertyChanged("WordUy");
				this.OnWordUyChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUyCn")]
public partial class TUyCn : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _WordUy;
	
	private string _WordCn;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnWordUyChanging(string value);
    partial void OnWordUyChanged();
    partial void OnWordCnChanging(string value);
    partial void OnWordCnChanged();
    #endregion
	
	public TUyCn()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordUy", DbType="NChar(255)")]
	public string WordUy
	{
		get
		{
			return this._WordUy;
		}
		set
		{
			if ((this._WordUy != value))
			{
				this.OnWordUyChanging(value);
				this.SendPropertyChanging();
				this._WordUy = value;
				this.SendPropertyChanged("WordUy");
				this.OnWordUyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordCn", DbType="NChar(255)")]
	public string WordCn
	{
		get
		{
			return this._WordCn;
		}
		set
		{
			if ((this._WordCn != value))
			{
				this.OnWordCnChanging(value);
				this.SendPropertyChanging();
				this._WordCn = value;
				this.SendPropertyChanged("WordCn");
				this.OnWordCnChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
